### ISSUE TITLE
feature request: open in terminal

### ISSUE THREAD

**Issue by dowcet** [donaghhorgan/rhythmbox-plugins-open-containing-folder#3]
I would love to have the option to open the folder in `gnome-terminal`, instead of with `xdg-open`. 

I imagine this would be pretty trivial for someone who knows what they are doing :) I tried hacking together my own plugin, but it failed.

**Comment by donaghhorgan** [comment]
I might be missing the point here, but why not just configure your [`xdg-open`](http://linux.die.net/man/1/xdg-open) to open `gnome-terminal` by default?

The reason I use `xdg-open` is because it provides cross platform support (e.g. it opens with `gnome-terminal` on GNOME, Dolphin on KDE, etc). If I hard-coded a version of the plugin for `gnome-terminal`, I'd then have to create separate versions to support individual file managers on different flavours of Linux.

**Comment by dowcet** [comment]
OK, thanks for the suggestion.
